/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projekakhir;

import java.sql.Timestamp;
import java.sql.Date;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import projekakhir.dao.PesananDatabaseOperation;
import projekakhir.model.Pesanan;
import projekakhir.utils.Utils;

/**
 *
 * @author Ismail
 */
public class DetailForm extends javax.swing.JFrame {

    /**
     * Creates new form DetailForm
     */
    private String kodePesanan;
    private Pesanan pesanan = new Pesanan();
    PesananDatabaseOperation pdo = new PesananDatabaseOperation();
    SimpleDateFormat sdf = new SimpleDateFormat("HH:mm");
    Utils utils = new Utils();

    public DetailForm(String kodePesanan) {
        this.kodePesanan = kodePesanan;
        initComponents();
        showPesanan(kodePesanan);
    }

    public DetailForm() {
        System.out.println(kodePesanan);
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        buatPesananLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        namaTeamFieldDetail = new javax.swing.JTextField();
        tanggalMainDetail = new com.toedter.calendar.JDateChooser();
        jamMulaiBoxDetail = new javax.swing.JComboBox<>();
        jamSelesaiBoxDetail = new javax.swing.JComboBox<>();
        dpFieldDetail = new javax.swing.JTextField();
        btnDelete = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        statusBoxDetail = new javax.swing.JComboBox<>();
        kodePesananField = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        kodeMemberDetail = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(162, 155, 254));

        buatPesananLabel.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        buatPesananLabel.setForeground(new java.awt.Color(45, 52, 54));
        buatPesananLabel.setText("Detail Pesanan");
        buatPesananLabel.setIconTextGap(15);
        buatPesananLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buatPesananLabelMouseClicked(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(45, 52, 54));
        jSeparator1.setForeground(new java.awt.Color(45, 52, 54));
        jSeparator1.setToolTipText("");
        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(45, 52, 54), 4));

        jLabel15.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(45, 52, 54));
        jLabel15.setText("Nama Team");
        jLabel15.setIconTextGap(15);

        jLabel16.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(45, 52, 54));
        jLabel16.setText("Tanggal Main");
        jLabel16.setIconTextGap(15);

        jLabel19.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(45, 52, 54));
        jLabel19.setText("Jam Mulai");
        jLabel19.setIconTextGap(15);

        jLabel20.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(45, 52, 54));
        jLabel20.setText("Jam Selesai");
        jLabel20.setIconTextGap(15);

        jLabel21.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(45, 52, 54));
        jLabel21.setText("DP");
        jLabel21.setIconTextGap(15);

        btnUpdate.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        namaTeamFieldDetail.setEditable(false);
        namaTeamFieldDetail.setEnabled(false);

        jamMulaiBoxDetail.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jamMulaiBoxDetail.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00" }));

        jamSelesaiBoxDetail.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jamSelesaiBoxDetail.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00" }));

        btnDelete.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        btnDelete.setText("Hapus");
        btnDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(45, 52, 54));
        jLabel22.setText("Status");
        jLabel22.setIconTextGap(15);

        statusBoxDetail.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        statusBoxDetail.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Diproses", "Belum Lunas", "Selesai" }));

        kodePesananField.setEditable(false);

        jLabel17.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(45, 52, 54));
        jLabel17.setText("Kode Pesanan");
        jLabel17.setIconTextGap(15);

        jLabel23.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(45, 52, 54));
        jLabel23.setText("Kode Member");
        jLabel23.setIconTextGap(15);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnUpdate)
                        .addGap(18, 18, 18)
                        .addComponent(btnDelete))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGap(29, 29, 29)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(buatPesananLabel)
                                    .addComponent(kodePesananField, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(namaTeamFieldDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(tanggalMainDetail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jamMulaiBoxDetail, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jamSelesaiBoxDetail, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(dpFieldDetail, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel21)
                                                .addComponent(jLabel15)
                                                .addComponent(jLabel16)
                                                .addComponent(jLabel19)
                                                .addComponent(jLabel20)
                                                .addComponent(jLabel22))
                                            .addGap(94, 94, 94))
                                        .addComponent(statusBoxDetail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jLabel17)))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(31, 31, 31)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel23)
                                .addComponent(kodeMemberDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(4, 4, 4))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buatPesananLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(kodePesananField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(namaTeamFieldDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tanggalMainDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addGap(3, 3, 3)
                .addComponent(jamMulaiBoxDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20)
                .addGap(5, 5, 5)
                .addComponent(jamSelesaiBoxDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dpFieldDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusBoxDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(kodeMemberDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buatPesananLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buatPesananLabelMouseClicked


    }//GEN-LAST:event_buatPesananLabelMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed

        //get data from form
        String kodePesanan = pesanan.getKodePesanan();
        String namaTeam = pesanan.getNamaTeam();
        int jam1Box = jamMulaiBoxDetail.getSelectedIndex() + 8;
        int jam2Box = jamSelesaiBoxDetail.getSelectedIndex() + 9;

        Timestamp ts = utils.getTimestamp(tanggalMainDetail, jam1Box);
        Timestamp ts2 = utils.getTimestamp(tanggalMainDetail, jam2Box);

        int dp = Integer.valueOf(dpFieldDetail.getText());
        String status = statusBoxDetail.getSelectedItem().toString();
        String kodeMember = kodeMemberDetail.getText();

        pesanan = new Pesanan(kodeMember, namaTeam, status, kodePesanan, ts, ts2, dp);
        System.out.println("Sukses");
        pdo.updatePesananByKodePesanan(pesanan, kodePesanan);
        JOptionPane.showMessageDialog(this, "Data berhasil diubah");
        this.setVisible(false);

    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int result = JOptionPane.showConfirmDialog(this, "Hapus data ini? ");
        if (result == 0) {
            pdo.deletePesananByKodePesanan(kodePesanan);
                    JOptionPane.showMessageDialog(this, "Data berhasil dihapus");
            this.setVisible(false);
        }


    }//GEN-LAST:event_btnDeleteActionPerformed

    // ------ Custom Function --------
    private void showPesanan(String kodePesanan) {

        pesanan = pdo.getPesananByKodePesanan(kodePesanan);

        // kode pesanan dan nama team
        kodePesananField.setText(pesanan.getKodePesanan());
        namaTeamFieldDetail.setText(pesanan.getNamaTeam());

        //jam mulai
        Timestamp tsMulai = pesanan.getJamMulai();
        Date dateMulai = new Date(tsMulai.getTime());
        String mulai = sdf.format(dateMulai);
        System.out.println(mulai);
        jamMulaiBoxDetail.setSelectedItem(mulai);

        //set tanggal main
        tanggalMainDetail.setDate(dateMulai);

        //jam selesai
        Timestamp tsSelesai = pesanan.getJamSelesai();
        Date dateSelesai = new Date(tsSelesai.getTime());
        String selesai = sdf.format(dateSelesai);
        jamSelesaiBoxDetail.setSelectedItem(selesai);

        //dp
        int dp = pesanan.getDp();
        dpFieldDetail.setText(String.valueOf(dp));

        //status
        String status = pesanan.getStatus();
        statusBoxDetail.setSelectedItem(status);

        //status
        String kodeMember = pesanan.getKodeMember();
        kodeMemberDetail.setText(kodeMember);

    }

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Windows".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(DetailForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(DetailForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(DetailForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(DetailForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new DetailForm().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel buatPesananLabel;
    private javax.swing.JTextField dpFieldDetail;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox<String> jamMulaiBoxDetail;
    private javax.swing.JComboBox<String> jamSelesaiBoxDetail;
    private javax.swing.JTextField kodeMemberDetail;
    private javax.swing.JTextField kodePesananField;
    private javax.swing.JTextField namaTeamFieldDetail;
    private javax.swing.JComboBox<String> statusBoxDetail;
    private com.toedter.calendar.JDateChooser tanggalMainDetail;
    // End of variables declaration//GEN-END:variables
}
