/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projekakhir;

import java.sql.Connection;
import java.sql.Timestamp;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import projekakhir.dao.MemberDatabaseOperation;
import projekakhir.dao.PesananDatabaseOperation;
import projekakhir.model.Member;
import projekakhir.model.Pesanan;
import projekakhir.utils.Constants;
import projekakhir.utils.Utils;

/**
 *
 * @author Ismail
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    Utils utils = new Utils();
    SimpleDateFormat sdf = new SimpleDateFormat("dd MMM HH:mm:ss");
    Pesanan pesanan = new Pesanan();
    Member member = new Member();
    private static Connection conn;
    PesananDatabaseOperation pdo = new PesananDatabaseOperation();
    MemberDatabaseOperation mdo = new MemberDatabaseOperation();
    Locale locale = new Locale("in", "ID");
    NumberFormat formatRupiah = NumberFormat.getCurrencyInstance(locale);

    private String statusUD;

    DefaultTableModel modelTablePesanan;
    DefaultTableModel modelTableMember;

    private int clickedId = 0;

    public MainFrame() {

        initComponents();
        modelTablePesanan = (DefaultTableModel) pesananTable.getModel();
        modelTableMember = (DefaultTableModel) memberTable.getModel();
        switchVisibiltyPanelPesanan("input");
        jPanel4.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bodyPanel = new javax.swing.JPanel();
        menuPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnHome = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnPesanan = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnMember = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnKeluar = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        homePanel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        buatPesananLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        btnInputPesanan = new javax.swing.JButton();
        namaTeamField = new javax.swing.JTextField();
        tanggalMain = new com.toedter.calendar.JDateChooser();
        jamMulaiBox = new javax.swing.JComboBox<>();
        jamSelesaiBox = new javax.swing.JComboBox<>();
        dpField = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        kodeMemberField = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        konfirmasiPesananLabel = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel18 = new javax.swing.JLabel();
        btnKonfirmasi = new javax.swing.JButton();
        kodePesananField = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        sisaBayarField = new javax.swing.JTextField();
        dp2Field = new javax.swing.JTextField();
        dp2 = new javax.swing.JLabel();
        totalBayar2Field = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        sisaBayarField1 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        btnLunasiPembayaran = new javax.swing.JButton();
        pesananPanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        pesananTable = new javax.swing.JTable();
        jLabel25 = new javax.swing.JLabel();
        statusBox = new javax.swing.JComboBox<>();
        searchPesananField = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        btnRefresh = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        pendapatanField = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        lamaSewaField = new javax.swing.JTextField();
        memberPanel = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        memberTable = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        namaMemberField = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        kontakMemberField = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        alamatMemberField = new javax.swing.JTextField();
        btnUpdateMember = new javax.swing.JButton();
        btnHapusMember = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        kodeMember = new javax.swing.JTextField();
        btnInputMember = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ismail Futsal Booking App - Tugas Akhir");
        setResizable(false);

        bodyPanel.setBackground(new java.awt.Color(162, 155, 254));

        menuPanel.setBackground(new java.awt.Color(102, 0, 255));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(45, 52, 54));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projekakhir/icon/kisspng-football-player-computer-icons-futsal-5b3b109e3126e1.7677632515305975342013 (1).png"))); // NOI18N
        jLabel7.setIconTextGap(15);

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(45, 52, 54));
        jLabel8.setText("Futsal Hall");
        jLabel8.setIconTextGap(15);

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(45, 52, 54));
        jLabel9.setText("Ismail");
        jLabel9.setIconTextGap(15);

        btnHome.setBackground(new java.awt.Color(102, 0, 255));
        btnHome.setPreferredSize(new java.awt.Dimension(0, 50));
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHomeMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(45, 52, 54));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projekakhir/icon/home-interface-symbol.png"))); // NOI18N
        jLabel1.setText("Home");
        jLabel1.setIconTextGap(16);

        javax.swing.GroupLayout btnHomeLayout = new javax.swing.GroupLayout(btnHome);
        btnHome.setLayout(btnHomeLayout);
        btnHomeLayout.setHorizontalGroup(
            btnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnHomeLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
        );
        btnHomeLayout.setVerticalGroup(
            btnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        btnPesanan.setBackground(new java.awt.Color(102, 0, 255));
        btnPesanan.setPreferredSize(new java.awt.Dimension(0, 50));
        btnPesanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPesananMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(45, 52, 54));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projekakhir/icon/list-with-numbers-interface-option.png"))); // NOI18N
        jLabel2.setText("Data Pesanan");
        jLabel2.setIconTextGap(16);

        javax.swing.GroupLayout btnPesananLayout = new javax.swing.GroupLayout(btnPesanan);
        btnPesanan.setLayout(btnPesananLayout);
        btnPesananLayout.setHorizontalGroup(
            btnPesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPesananLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        btnPesananLayout.setVerticalGroup(
            btnPesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        btnMember.setBackground(new java.awt.Color(102, 0, 255));
        btnMember.setPreferredSize(new java.awt.Dimension(0, 50));
        btnMember.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMemberMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(45, 52, 54));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projekakhir/icon/member.png"))); // NOI18N
        jLabel4.setText("Member");
        jLabel4.setIconTextGap(16);

        javax.swing.GroupLayout btnMemberLayout = new javax.swing.GroupLayout(btnMember);
        btnMember.setLayout(btnMemberLayout);
        btnMemberLayout.setHorizontalGroup(
            btnMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnMemberLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );
        btnMemberLayout.setVerticalGroup(
            btnMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        btnKeluar.setBackground(new java.awt.Color(102, 0, 255));
        btnKeluar.setPreferredSize(new java.awt.Dimension(0, 50));
        btnKeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKeluarMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(45, 52, 54));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projekakhir/icon/logout.png"))); // NOI18N
        jLabel5.setText("Keluar");
        jLabel5.setIconTextGap(16);

        javax.swing.GroupLayout btnKeluarLayout = new javax.swing.GroupLayout(btnKeluar);
        btnKeluar.setLayout(btnKeluarLayout);
        btnKeluarLayout.setHorizontalGroup(
            btnKeluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnKeluarLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
        );
        btnKeluarLayout.setVerticalGroup(
            btnKeluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnPesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)))
            .addComponent(btnMember, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(43, 43, 43)
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPesanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(247, Short.MAX_VALUE))
        );

        mainPanel.setBackground(new java.awt.Color(108, 92, 231));
        mainPanel.setLayout(new java.awt.CardLayout());

        homePanel.setBackground(new java.awt.Color(162, 155, 254));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(45, 52, 54));
        jLabel10.setText("Home");
        jLabel10.setIconTextGap(15);

        jPanel1.setBackground(new java.awt.Color(162, 155, 254));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 652, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 91, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(162, 155, 254));

        buatPesananLabel.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        buatPesananLabel.setForeground(new java.awt.Color(45, 52, 54));
        buatPesananLabel.setText("Buat Pesanan");
        buatPesananLabel.setIconTextGap(15);
        buatPesananLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buatPesananLabelMouseClicked(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(45, 52, 54));
        jSeparator1.setForeground(new java.awt.Color(45, 52, 54));
        jSeparator1.setToolTipText("");
        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(45, 52, 54), 4));

        jLabel15.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(45, 52, 54));
        jLabel15.setText("Nama Team");
        jLabel15.setIconTextGap(15);

        jLabel16.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(45, 52, 54));
        jLabel16.setText("Tanggal Main");
        jLabel16.setIconTextGap(15);

        jLabel19.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(45, 52, 54));
        jLabel19.setText("Jam Mulai");
        jLabel19.setIconTextGap(15);

        jLabel20.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(45, 52, 54));
        jLabel20.setText("Jam Selesai");
        jLabel20.setIconTextGap(15);

        jLabel21.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(45, 52, 54));
        jLabel21.setText("DP");
        jLabel21.setIconTextGap(15);

        btnInputPesanan.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        btnInputPesanan.setText("Input Pesanan");
        btnInputPesanan.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnInputPesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInputPesananActionPerformed(evt);
            }
        });

        jamMulaiBox.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jamMulaiBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00" }));

        jamSelesaiBox.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jamSelesaiBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00" }));

        jLabel17.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(45, 52, 54));
        jLabel17.setText("Kode Member");
        jLabel17.setIconTextGap(15);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(namaTeamField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kodeMemberField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tanggalMain, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jamMulaiBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jamSelesaiBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dpField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(94, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btnInputPesanan)
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buatPesananLabel))
                        .addGap(36, 36, 36))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buatPesananLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kodeMemberField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namaTeamField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tanggalMain, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addGap(3, 3, 3)
                .addComponent(jamMulaiBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20)
                .addGap(5, 5, 5)
                .addComponent(jamSelesaiBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dpField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnInputPesanan)
                .addGap(8, 8, 8))
        );

        jPanel3.setBackground(new java.awt.Color(162, 155, 254));

        konfirmasiPesananLabel.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        konfirmasiPesananLabel.setForeground(new java.awt.Color(45, 52, 54));
        konfirmasiPesananLabel.setText("Konfirmasi Pesanan");
        konfirmasiPesananLabel.setIconTextGap(15);
        konfirmasiPesananLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                konfirmasiPesananLabelMouseClicked(evt);
            }
        });

        jSeparator2.setBackground(new java.awt.Color(45, 52, 54));
        jSeparator2.setForeground(new java.awt.Color(45, 52, 54));
        jSeparator2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(162, 155, 254), 4));

        jLabel18.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(45, 52, 54));
        jLabel18.setText("Kode Pesanan");
        jLabel18.setIconTextGap(15);

        btnKonfirmasi.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        btnKonfirmasi.setText("Konfirmasi");
        btnKonfirmasi.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnKonfirmasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKonfirmasiActionPerformed(evt);
            }
        });

        kodePesananField.setDisabledTextColor(new java.awt.Color(45, 52, 54));

        jPanel4.setBackground(new java.awt.Color(162, 155, 254));

        jLabel22.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(45, 52, 54));
        jLabel22.setText("Sisa Bayar");
        jLabel22.setIconTextGap(15);

        sisaBayarField.setEditable(false);
        sisaBayarField.setDisabledTextColor(new java.awt.Color(45, 52, 54));
        sisaBayarField.setEnabled(false);

        dp2Field.setEditable(false);
        dp2Field.setDisabledTextColor(new java.awt.Color(45, 52, 54));
        dp2Field.setEnabled(false);

        dp2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        dp2.setForeground(new java.awt.Color(45, 52, 54));
        dp2.setText("DP");
        dp2.setIconTextGap(15);

        totalBayar2Field.setEditable(false);
        totalBayar2Field.setDisabledTextColor(new java.awt.Color(45, 52, 54));
        totalBayar2Field.setEnabled(false);

        jLabel28.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(45, 52, 54));
        jLabel28.setText("Total Bayar");
        jLabel28.setIconTextGap(15);

        sisaBayarField1.setDisabledTextColor(new java.awt.Color(45, 52, 54));

        jLabel24.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(45, 52, 54));
        jLabel24.setText("Masukan Sisa Bayar");
        jLabel24.setIconTextGap(15);

        btnLunasiPembayaran.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        btnLunasiPembayaran.setText("Lunasi Pembayaran");
        btnLunasiPembayaran.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnLunasiPembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLunasiPembayaranActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnLunasiPembayaran))
                    .addComponent(jLabel22)
                    .addComponent(sisaBayarField, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dp2)
                    .addComponent(dp2Field, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28)
                    .addComponent(totalBayar2Field, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(sisaBayarField1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(dp2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dp2Field, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalBayar2Field, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sisaBayarField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sisaBayarField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLunasiPembayaran)
                .addContainerGap(228, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(konfirmasiPesananLabel)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                    .addGap(41, 41, 41)
                                    .addComponent(btnKonfirmasi)))
                            .addComponent(jLabel18)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(kodePesananField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(konfirmasiPesananLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kodePesananField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnKonfirmasi)
                .addGap(46, 46, 46)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(39, 39, 39))
        );

        jSeparator2.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout homePanelLayout = new javax.swing.GroupLayout(homePanel);
        homePanel.setLayout(homePanelLayout);
        homePanelLayout.setHorizontalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(homePanelLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addContainerGap())
        );
        homePanelLayout.setVerticalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.add(homePanel, "card2");

        pesananPanel.setBackground(new java.awt.Color(162, 155, 254));
        pesananPanel.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(45, 52, 54));
        jLabel11.setText("Data Pesanan");
        jLabel11.setIconTextGap(15);

        pesananTable.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        pesananTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Kode Pesanan", "Tanggal Pesan", "Nama Team", "Lama Sewa", "Status", "Total Bayar"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        pesananTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pesananTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(pesananTable);
        if (pesananTable.getColumnModel().getColumnCount() > 0) {
            pesananTable.getColumnModel().getColumn(0).setPreferredWidth(7);
        }

        jLabel25.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(45, 52, 54));
        jLabel25.setText("Status");
        jLabel25.setIconTextGap(15);

        statusBox.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        statusBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Semua", "Diproses", "Belum Lunas", "Selesai" }));
        statusBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusBoxActionPerformed(evt);
            }
        });

        searchPesananField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchPesananFieldKeyReleased(evt);
            }
        });

        jLabel33.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(45, 52, 54));
        jLabel33.setText("Cari Team");
        jLabel33.setIconTextGap(15);

        btnRefresh.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnRefresh.setText("Refresh");
        btnRefresh.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnRefresh.setPreferredSize(new java.awt.Dimension(86, 25));
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        jLabel34.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(45, 52, 54));
        jLabel34.setText("Total Pendapatan");
        jLabel34.setIconTextGap(15);

        pendapatanField.setEditable(false);

        jLabel35.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(45, 52, 54));
        jLabel35.setText("Total Lama sewa");
        jLabel35.setIconTextGap(15);

        lamaSewaField.setEditable(false);

        javax.swing.GroupLayout pesananPanelLayout = new javax.swing.GroupLayout(pesananPanel);
        pesananPanel.setLayout(pesananPanelLayout);
        pesananPanelLayout.setHorizontalGroup(
            pesananPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pesananPanelLayout.createSequentialGroup()
                .addGroup(pesananPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pesananPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel35)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lamaSewaField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pesananPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(pesananPanelLayout.createSequentialGroup()
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel34)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(pendapatanField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pesananPanelLayout.createSequentialGroup()
                            .addGap(32, 32, 32)
                            .addGroup(pesananPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pesananPanelLayout.createSequentialGroup()
                                    .addComponent(jLabel25)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(statusBox, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(187, 187, 187)
                                    .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel33)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(searchPesananField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel11)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 682, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        pesananPanelLayout.setVerticalGroup(
            pesananPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pesananPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pesananPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel25)
                    .addComponent(jLabel33)
                    .addComponent(searchPesananField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pesananPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(statusBox)
                        .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(pesananPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pendapatanField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34))
                .addGap(18, 18, 18)
                .addGroup(pesananPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lamaSewaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35))
                .addGap(261, 261, 261))
        );

        mainPanel.add(pesananPanel, "card3");

        memberPanel.setBackground(new java.awt.Color(162, 155, 254));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(45, 52, 54));
        jLabel13.setText("Tambah Member");
        jLabel13.setIconTextGap(15);

        memberTable.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        memberTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Kode Member", "Nama Member", "Alamat", "Kontak"
            }
        ));
        memberTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                memberTableMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(memberTable);

        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(45, 52, 54));
        jLabel14.setText("Daftar Member");
        jLabel14.setIconTextGap(15);

        jLabel23.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(45, 52, 54));
        jLabel23.setText("Nama Team");
        jLabel23.setIconTextGap(15);

        jLabel31.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(45, 52, 54));
        jLabel31.setText("Kontak");
        jLabel31.setIconTextGap(15);

        jLabel32.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(45, 52, 54));
        jLabel32.setText("Alamat");
        jLabel32.setIconTextGap(15);

        btnUpdateMember.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        btnUpdateMember.setText("Update");
        btnUpdateMember.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnUpdateMember.setEnabled(false);
        btnUpdateMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateMemberActionPerformed(evt);
            }
        });

        btnHapusMember.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        btnHapusMember.setText("Hapus");
        btnHapusMember.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnHapusMember.setEnabled(false);
        btnHapusMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusMemberActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(45, 52, 54));
        jLabel26.setText("Kode Member");
        jLabel26.setIconTextGap(15);

        kodeMember.setEditable(false);
        kodeMember.setEnabled(false);

        btnInputMember.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        btnInputMember.setText("Tambah");
        btnInputMember.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnInputMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInputMemberActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout memberPanelLayout = new javax.swing.GroupLayout(memberPanel);
        memberPanel.setLayout(memberPanelLayout);
        memberPanelLayout.setHorizontalGroup(
            memberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(memberPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(memberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addComponent(jLabel13)
                    .addComponent(namaMemberField, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32)
                    .addComponent(alamatMemberField, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31)
                    .addComponent(kontakMemberField, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26)
                    .addComponent(kodeMember, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(memberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnInputMember, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, memberPanelLayout.createSequentialGroup()
                            .addComponent(btnUpdateMember, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnHapusMember, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(41, 41, 41))
            .addGroup(memberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(memberPanelLayout.createSequentialGroup()
                    .addGap(42, 42, 42)
                    .addComponent(jLabel14)
                    .addContainerGap(515, Short.MAX_VALUE)))
        );
        memberPanelLayout.setVerticalGroup(
            memberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(memberPanelLayout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addGroup(memberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(memberPanelLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kodeMember, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(namaMemberField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(alamatMemberField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kontakMemberField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnInputMember)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(memberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnUpdateMember)
                            .addComponent(btnHapusMember))))
                .addContainerGap(170, Short.MAX_VALUE))
            .addGroup(memberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(memberPanelLayout.createSequentialGroup()
                    .addGap(31, 31, 31)
                    .addComponent(jLabel14)
                    .addContainerGap(639, Short.MAX_VALUE)))
        );

        mainPanel.add(memberPanel, "card4");

        javax.swing.GroupLayout bodyPanelLayout = new javax.swing.GroupLayout(bodyPanel);
        bodyPanel.setLayout(bodyPanelLayout);
        bodyPanelLayout.setHorizontalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyPanelLayout.createSequentialGroup()
                .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        bodyPanelLayout.setVerticalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
            .addGroup(bodyPanelLayout.createSequentialGroup()
                .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseClicked

        //reset background and selected panel
        hidePanel();
        resetBackgroundButton();
        homePanel.setVisible(true);
        btnHome.setBackground(new java.awt.Color(162, 155, 254));


    }//GEN-LAST:event_btnHomeMouseClicked

    private void btnPesananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesananMouseClicked
        //reset background and selected panel
        hidePanel();
        resetBackgroundButton();
        pesananPanel.setVisible(true);
        btnPesanan.setBackground(new java.awt.Color(162, 155, 254));

        //tampilkan data pesanan kedalam tabel
        List<Pesanan> pesananList = pdo.getListPesananByStatus("Semua");

        tampilkanPesanan(pesananList);


    }//GEN-LAST:event_btnPesananMouseClicked

    private void btnMemberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMemberMouseClicked
        //reset background 
        hidePanel();
        resetBackgroundButton();
        memberPanel.setVisible(true);
        btnMember.setBackground(new java.awt.Color(162, 155, 254));

        List<Member> member = mdo.getAllMember();
        tampilkanMember(member);


    }//GEN-LAST:event_btnMemberMouseClicked

    private void btnInputPesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInputPesananActionPerformed

        String kodeMember = kodeMemberField.getText();
        String namaTeam = namaTeamField.getText();
        int jam1Box = jamMulaiBox.getSelectedIndex() + 8;
        int jam2Box = jamSelesaiBox.getSelectedIndex() + 9;

        Timestamp ts = utils.getTimestamp(tanggalMain, jam1Box);
        Timestamp ts2 = utils.getTimestamp(tanggalMain, jam2Box);

        int dp = Integer.valueOf(dpField.getText());

        pesanan = new Pesanan(kodeMember, namaTeam, ts, ts2, dp);

        pdo.insertPesanan(pesanan);
        int sisaBayar = pdo.cariSisaBayar(pesanan.getKodePesanan(), pesanan.getKodeMember());
        pdo.insertSisaBayar(sisaBayar, pesanan.getKodePesanan());

        JOptionPane.showMessageDialog(this, "Berhasil memesan dengan kode pesan: " + pesanan.getKodePesanan());

        kodeMemberField.setText("");
        namaTeamField.setText("");
        dpField.setText("");

    }//GEN-LAST:event_btnInputPesananActionPerformed

    private void btnKonfirmasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKonfirmasiActionPerformed

        String kodePesanan = kodePesananField.getText();
        pesanan = pdo.getPesananByKodePesanan(kodePesanan);
        pdo.setStatus(kodePesanan, Constants.BELUM_LUNAS);
        int sisaBayar = pesanan.getSisaBayar();
        if (sisaBayar == 0) {
            sisaBayarField.setText("");
            dp2Field.setText("");
            totalBayar2Field.setText("");
        } else {
            sisaBayarField.setText(String.valueOf(formatRupiah.format(sisaBayar)));
            dp2Field.setText(String.valueOf(formatRupiah.format(pesanan.getDp())));
            totalBayar2Field.setText(String.valueOf(formatRupiah.format(pesanan.getDp() + sisaBayar)));
            jPanel4.setVisible(true);
        }
        kodePesananField.setText("");
        JOptionPane.showMessageDialog(this, "Pesanan berhasil dikonfirmasi");

    }//GEN-LAST:event_btnKonfirmasiActionPerformed

    private void buatPesananLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buatPesananLabelMouseClicked

        //jika textfield buat pesanan di klik, matikan panel konfirmasi pesanan dan ganti warna separator
        String action = "input";
        switchVisibiltyPanelPesanan(action);
        jPanel4.setVisible(false);
    }//GEN-LAST:event_buatPesananLabelMouseClicked

    private void konfirmasiPesananLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_konfirmasiPesananLabelMouseClicked

        //jika textfield konfirmasi di klik, matikan panel buat pesanan dan ganti warna separator
        String action = "konifrmasi";
        switchVisibiltyPanelPesanan(action);


    }//GEN-LAST:event_konfirmasiPesananLabelMouseClicked

    private void btnLunasiPembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLunasiPembayaranActionPerformed
        String kodePesanan = pesanan.getKodePesanan();
        int sisaBayar = pesanan.getSisaBayar();
        int sisaBayarInput = Integer.parseInt(sisaBayarField1.getText());

        if (sisaBayarInput >= sisaBayar) {
            pdo.setStatus(kodePesanan, Constants.SELESAI);
            JOptionPane.showMessageDialog(this, "Pesanan " + kodePesanan + " selesai.");
            sisaBayarField.setText("");
            dp2Field.setText("");
            totalBayar2Field.setText("");
            if (sisaBayarInput > sisaBayar) {
                int kembalian = sisaBayarInput - sisaBayar;
                JOptionPane.showMessageDialog(this, "Kembalian : " + kembalian);
            }
        } else if (sisaBayarInput < sisaBayar) {
            JOptionPane.showMessageDialog(this, "uang kurang: ");
        }

        sisaBayarField1.setText("");


    }//GEN-LAST:event_btnLunasiPembayaranActionPerformed

    private void btnKeluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKeluarMouseClicked
        // TODO add your handling code here:

        resetBackgroundButton();
        btnKeluar.setBackground(new java.awt.Color(162, 155, 254));
        int keluar = JOptionPane.showConfirmDialog(this, "Apakah anda ingn keluar? ");
        if (keluar == 0) {
            this.dispose();
            new Login().setVisible(true);

        }


    }//GEN-LAST:event_btnKeluarMouseClicked

    private void btnUpdateMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateMemberActionPerformed

        String kodeMemberUpdate = kodeMember.getText();
        String namaMember = namaMemberField.getText();
        String alamat = alamatMemberField.getText();
        String kontak = kontakMemberField.getText();
        Member memberUpdate = new Member(kodeMemberUpdate, namaMember, kontak, alamat);
        mdo.updateMember(memberUpdate, kodeMemberUpdate);

        btnInputMember.setEnabled(true);
        btnUpdateMember.setEnabled(false);
        btnHapusMember.setEnabled(false);
        jLabel13.setText("Tambah Member");
        kodeMember.setText("");
        namaMemberField.setText("");
        alamatMemberField.setText("");
        kontakMemberField.setText("");

        JOptionPane.showMessageDialog(this, "Data berhasil diubah");
        showAllMember();


    }//GEN-LAST:event_btnUpdateMemberActionPerformed

    private void pesananTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pesananTableMouseClicked

        String kodePesanan = modelTablePesanan.getValueAt(pesananTable.getSelectedRow(), 1).toString();
        System.out.println(kodePesanan);
        new DetailForm(kodePesanan).setVisible(true);
    }//GEN-LAST:event_pesananTableMouseClicked

    private void statusBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusBoxActionPerformed

        String status = statusBox.getSelectedItem().toString();

        List<Pesanan> pesananList;

        pesananList = pdo.getListPesananByStatus(status);

        tampilkanPesanan(pesananList);


    }//GEN-LAST:event_statusBoxActionPerformed

    private void searchPesananFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchPesananFieldKeyReleased
        // TODO add your handling code here:

        String key = searchPesananField.getText();
        String status = statusBox.getSelectedItem().toString();
        List<Pesanan> hasilPencarian = pdo.searchPesanan(status, key);
        tampilkanPesanan(hasilPencarian);

    }//GEN-LAST:event_searchPesananFieldKeyReleased

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        tampilkanPesanan(pdo.getListPesananByStatus("Semua"));
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnHapusMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusMemberActionPerformed

        String kodeMemberUpdate = kodeMember.getText();

        int hapus = JOptionPane.showConfirmDialog(this, "Hapus data? ");
        if (hapus == 0) {
            mdo.deleteMemberByKodeMember(kodeMemberUpdate);
            JOptionPane.showMessageDialog(this, "Data berhasil di hapus");

            showAllMember();
        }


    }//GEN-LAST:event_btnHapusMemberActionPerformed

    private void memberTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_memberTableMouseClicked

        String kodeMember = modelTableMember.getValueAt(memberTable.getSelectedRow(), 1).toString();
        Member member = mdo.getMemberByIdMember(kodeMember);

        this.kodeMember.setText(member.getIdMember());
        namaMemberField.setText(member.getNamaMember());
        alamatMemberField.setText(member.getAlamat());
        kontakMemberField.setText(member.getKontak());
        btnHapusMember.setEnabled(true);
        btnUpdateMember.setEnabled(true);
        btnInputMember.setEnabled(false);
        jLabel13.setText("Edit member");


    }//GEN-LAST:event_memberTableMouseClicked

    private void btnInputMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInputMemberActionPerformed
        String namaTeamMember = namaMemberField.getText();
        String alamatTeam = alamatMemberField.getText();
        String kontakTeam = kontakMemberField.getText();

        member = new Member(namaTeamMember, kontakTeam, alamatTeam);
        mdo.insertMember(member);

        JOptionPane.showMessageDialog(this, "Berhasil tambah member: " + namaTeamMember);

        showAllMember();

        namaMemberField.setText("");
        alamatMemberField.setText("");
        kontakMemberField.setText("");
    }//GEN-LAST:event_btnInputMemberActionPerformed

    // ------------------------  CUSTOM FUNCTION  ---------------------------
    private void hidePanel() {
        homePanel.setVisible(false);
        pesananPanel.setVisible(false);
        memberPanel.setVisible(false);

    }

    private void resetBackgroundButton() {
        btnHome.setBackground(new java.awt.Color(102, 0, 255));
        btnPesanan.setBackground(new java.awt.Color(102, 0, 255));
        btnMember.setBackground(new java.awt.Color(102, 0, 255));
        btnKeluar.setBackground(new java.awt.Color(102, 0, 255));
    }

    private void switchVisibiltyPanelPesanan(String action) {

        if (action.equals("input")) {
            jSeparator2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(162, 155, 254), 4));
            jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(45, 52, 54), 4));

            kodePesananField.setEnabled(false);
            btnKonfirmasi.setEnabled(false);
            namaTeamField.setEnabled(true);
            tanggalMain.setEnabled(true);
            jamMulaiBox.setEnabled(true);
            jamSelesaiBox.setEnabled(true);
            dpField.setEnabled(true);
            btnInputPesanan.setEnabled(true);
        } else {
            jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(162, 155, 254), 4));
            jSeparator2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(45, 52, 54), 4));

            kodePesananField.setEnabled(true);
            btnKonfirmasi.setEnabled(true);
            namaTeamField.setEnabled(false);
            tanggalMain.setEnabled(false);
            jamMulaiBox.setEnabled(false);
            jamSelesaiBox.setEnabled(false);
            dpField.setEnabled(false);
            btnInputPesanan.setEnabled(false);
        }

    }

    private void tampilkanPesanan(List<Pesanan> pesananList) {

        modelTablePesanan.setRowCount(0);
        SimpleDateFormat sdf = new SimpleDateFormat("dd MMM");
        int no = 1;
        for (Pesanan pesanan1 : pesananList) {

            Date tanggal = utils.timeStampToDate(pesanan1.getJamMulai());
            String lamaMain = String.valueOf(utils.getLamaMain(pesanan1)) + " Jam";
            int totalBayar = pesanan1.getDp() + pesanan1.getSisaBayar();
            modelTablePesanan.addRow(new Object[]{no,
                pesanan1.getKodePesanan(),
                sdf.format(tanggal),
                pesanan1.getNamaTeam(),
                lamaMain,
                pesanan1.getStatus(),
                formatRupiah.format(totalBayar)
            });
            no++;
        }

        //menampilkan total penghasilan
        int totalPendapatan = pdo.getTotalPendapatan();
        pendapatanField.setText(formatRupiah.format(totalPendapatan));

        //menampilkan total lama sewa
        int totalLamaSewa = pdo.getTotalLamaSewa();
        lamaSewaField.setText(String.valueOf(totalLamaSewa) + " Jam");

    }

    private void tampilkanMember(List<Member> memberList) {

        modelTableMember.setRowCount(0);
        int no = 1;
        for (Member member1 : memberList) {
            modelTableMember.addRow(new Object[]{
                no,
                member1.getIdMember(),
                member1.getNamaMember(),
                member1.getAlamat(),
                member1.getKontak(),
                no++

            });
        }

    }

    private void showAllMember() {
        List<Member> member = mdo.getAllMember();
        tampilkanMember(member);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamatMemberField;
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JButton btnHapusMember;
    private javax.swing.JPanel btnHome;
    private javax.swing.JButton btnInputMember;
    private javax.swing.JButton btnInputPesanan;
    private javax.swing.JPanel btnKeluar;
    private javax.swing.JButton btnKonfirmasi;
    private javax.swing.JButton btnLunasiPembayaran;
    private javax.swing.JPanel btnMember;
    private javax.swing.JPanel btnPesanan;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnUpdateMember;
    private javax.swing.JLabel buatPesananLabel;
    private javax.swing.JLabel dp2;
    private javax.swing.JTextField dp2Field;
    private javax.swing.JTextField dpField;
    private javax.swing.JPanel homePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JComboBox<String> jamMulaiBox;
    private javax.swing.JComboBox<String> jamSelesaiBox;
    private javax.swing.JTextField kodeMember;
    private javax.swing.JTextField kodeMemberField;
    private javax.swing.JTextField kodePesananField;
    private javax.swing.JLabel konfirmasiPesananLabel;
    private javax.swing.JTextField kontakMemberField;
    private javax.swing.JTextField lamaSewaField;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel memberPanel;
    private javax.swing.JTable memberTable;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JTextField namaMemberField;
    private javax.swing.JTextField namaTeamField;
    private javax.swing.JTextField pendapatanField;
    private javax.swing.JPanel pesananPanel;
    private javax.swing.JTable pesananTable;
    private javax.swing.JTextField searchPesananField;
    private javax.swing.JTextField sisaBayarField;
    private javax.swing.JTextField sisaBayarField1;
    private javax.swing.JComboBox<String> statusBox;
    private com.toedter.calendar.JDateChooser tanggalMain;
    private javax.swing.JTextField totalBayar2Field;
    // End of variables declaration//GEN-END:variables
}
